### PR TITLE
Allow the configuration of an OIDC-Provider via Helm-chart

### PR DESCRIPTION
**Pull request by Andy2003**
resolves https://github.com/gravitee-io/issues/issues/4645

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @Andy2003 

Thanks for the PR. 

I'm just wondering how can we manage array of oidc here.

Any thoughts ?

**Comment by Andy2003** [comment]
we could move the whole yaml out into the values, so we just insert the yaml as is. But this will remove the ability to simple configure the chart via parameters

**Comment by Andy2003** [comment]
@brasseld Any opinion on my [commet](https://github.com/gravitee-io/helm-charts/pull/72#issuecomment-732254201)

**Comment by brasseld** [comment]
Sorry for being late on that one. I do agree with you.

I'll check the PR asap.

**Comment by Andy2003** [comment]
@brasseld I have added a 2nd configuration option, with which you can also configure multiple providers

**Pull request merged**
