### PR TITLE
Allow elasticsearch enable/disable through chart value

### PR DESCRIPTION
**Pull request by gs11**

### CODE REVIEW

**Comment by gs11** [comment]
Hm, API configmap would also need updating. How can I completely disable this in the config, just remove it?

>     analytics:
>       type: elasticsearch
>       elasticsearch:
>         endpoints:
>           - {{ .Values.es.protocol }}://{{ .Values.es.host }}:{{ .Values.es.port }}
>         index: {{ .Values.es.index }}
>         cluster: {{ .Values.es.cluster }}

**Comment by brasseld** [comment]
> API ConfigMap would also need updating. How can I completely disable this in the config, just remove it?
> 
> > ```
> > analytics:
> >   type: elasticsearch
> >   elasticsearch:
> >     endpoints:
> >       - {{ .Values.es.protocol }}://{{ .Values.es.host }}:{{ .Values.es.port }}
> >     index: {{ .Values.es.index }}
> >     cluster: {{ .Values.es.cluster }}
> > ```

Nop, I think there is already an issue (https://github.com/gravitee-io/issues/issues/945) about this point.

**Comment by gs11** [comment]
So it seems, completely removing ES would cause some errors in the UI/API but no worse than that. Will evaulate..

**Comment by gs11** [comment]
Tested but the API pod terminates after logging the same exception every 5 seconds.
` 12:35:57.494 [vert.x-eventloop-thread-0] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
java.net.UnknownHostException: failed to resolve 'apim-elastic-elasticsearch-coordinating-only' after 2 queries 
    at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:721)
    at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:663)
    at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:306)
    at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295)
    at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:636)
    at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:342)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
    at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:197)
    at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:180)
    at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:965)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748) `

**Comment by brasseld** [comment]
This PR is very old.

Closing it.

**Pull request closed without merging**
