### PR TITLE
Remove legacy Kube Controller

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

https://github.com/gravitee-io/issues/issues/8435

**Description**

Remove legacy Kube Controller

BREAKING CHANGE: kubeController is removed as it is no longer maintained and not working with last APIM

### CODE REVIEW

**Review by gaetanmaisse — COMMENTED** [review]
You need to update the CHANGELOG and Chart files to include the breaking changes there

**Comment by gaetanmaisse** [comment]
@ThibaudAV  Is there a GH or Jira ticket related to that?

**Comment by ThibaudAV** [comment]
> You need to update the CHANGELOG and Chart files to include the breaking changes there
And so I change major? I wonder because it's not working at the moment. It's more a clean unused code. but it changes the public interface 🤷‍♂️  

Is there a GH or Jira ticket related to that? 
maybe this one : https://github.com/gravitee-io/issues/issues/8435

**Comment by ThibaudAV** [comment]
Rebased. 
I did a minor but I don't really know if it's the best choice 
Maybe @leleueri perhaps the most relevant person to review this RP 🙏

**Review by leleueri — CHANGES_REQUESTED** [review]
The entry you defined into the CHANGELOG.md has to be reported here https://github.com/gravitee-io/helm-charts/pull/312/files#diff-855cce9133477850eb31705d7dc35ced0f9333fe7eaeb4dfe41d6624a407429cR23

**Review by leleueri — APPROVED** [review]

**Review by sebdevaux — APPROVED** [review]

**Pull request merged**
