### PR TITLE
Simplify configuration of jdbc driver and other plugins

### PR DESCRIPTION
**Pull request by Andy2003**
This change simplifies the configuration of:

**JDBC-repo**

```yaml
management:
  type: jdbc
```
and / or

```yaml
ratelimit:
  type: jdbc
```
_HINT: the jdbc-repo-plugin will only be downloaded for releases < 3.5.0 since after that it is already included into the normal distribution_

**JDBC-driver**

by just enabling `jdbc` for management and / or ratelimit and configuring:

```yaml
jdbc:
    driver: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.jar
```

**HTTP-Bridge-client**

by just configuring:

```yaml
management:
  type: http
```

**HTTP-Bridge-server**

by just configuring:

```yaml
gateway:
  services:
    bridge:
      enabled: true
```

**Redis**

by just configuring:

```yaml
management:
  type: redis
```
and / or

```yaml
ratelimit:
  type: redis
```

**Additional plugins**

by just configuring:

```yaml
api:
  additionalPlugins:
    - https://path_to_plugin
```

and / or 

```yaml
gateway:
  additionalPlugins:
    - https://path_to_plugin
```

relates to https://github.com/gravitee-io/issues/issues/4741

### CODE REVIEW

**Comment by Andy2003** [comment]
@brasseld / @aelamrani 
It would be great if you could check the PR.
And after this would it be possible to deploy the Helm Chart, so that I can refer to it for my further work.

**Comment by brasseld** [comment]
I'll probably do this evening, no worry.

I'm just asking myself if it makes sense to fully validate this PR as we are planning to deliver 3.5 with JDBC and HTTP bundled with Mongo.

**Comment by Andy2003** [comment]
> I'm just asking myself if it makes sense to fully validate this PR as we are planning to deliver 3.5 with JDBC and HTTP bundled with Mongo.

@brasseld Yes you should, b/c this PR

1. harmonizes also the provisioning for 
    * redis
    * bridge-http-server
    * bridge-http-client
2. will also work for releases < 3.5. where jdbc is included
3. I added the ability to provision custom plugins via a list of URLs

**Comment by brasseld** [comment]
Great job @Andy2003 👍

**Comment by Andy2003** [comment]
@brasseld would it be possible to deploy the Helm Chart, so that I can refer to it for my further work?

**Comment by brasseld** [comment]
Done

**Pull request merged**
