### PR TITLE
fix: Upgrade MongoDB and Elasticsearch for Helm Charts

### PR DESCRIPTION
**Pull request by kamiiiel**
**Issue**

https://graviteedevops.atlassian.net/browse/ARCH-155

**Description**

A small description of what you did in that PR.

**Additional context**

### CODE REVIEW

**Review by jgiovaresco — APPROVED** [review]

**Comment by brasseld** [comment]
Guys, I'm wondering if it's not the right time to increase the minor version as this change would not be compatible with previous MongoDB dependency. Wdyt @jgiovaresco @kamiiiel ?

**Review by brasseld — COMMENTED** [review]
@kamiiiel Can you please add a note stating that mongodb and elasticsearch usage from gravitee helm charts is not recommended and not ready for production usage and it's better to deploy these two separately from Gravitee.

**Review by brasseld — COMMENTED** [review]
I'm not sure if it's me who's doing something wrong but I'm not able to run Mongo properly and this one is never starting. 
Is there any pre-requisites when enabling Mongo or ES @kamiiiel

**Comment by kamiiiel** [comment]
> I'm not sure if it's me who's doing something wrong but I'm not able to run Mongo properly and this one is never starting. Is there any pre-requisites when enabling Mongo or ES @kamiiiel

No, there shouldn't be any pre-requirements. Do you get any error or something? You install it locally?

**Review by brasseld — APPROVED** [review]

**Pull request merged**
