### PR TITLE
feat(apim): added option to define tracing inside of ConfigMap

### PR DESCRIPTION
**Pull request by christianknell**
**Description**

I added values to define tracing options according to https://docs.gravitee.io/apim/3.x/apim_enable_opentracing_with_jaeger.html as well as the corresponding definition inside the configmap.

### CODE REVIEW

**Comment by phiz71** [comment]
Hello @christianknell! Thank you for your contribution 🙏🏻! May I ask you to add some tests regarding this new feature?
You can take an example on this file: https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/tests/gateway/configmap_mongodb_test.yaml

**Comment by christianknell** [comment]
Hey @phiz71 tests have been added

**Comment by phiz71** [comment]
Thank you @christianknell. At first glance, it looks good to me.
We will review your PR soon.

**Review by phiz71 — APPROVED** [review]

**Comment by phiz71** [comment]
Thanks again @christianknell 🙏🏻 
Your PR has been merged.
Your work will be available in the next release of our charts !

**Comment by phiz71** [comment]
@christianknell FYI, a 3.1.61 version of our APIM chart has been released ;)

**Comment by christianknell** [comment]
thanks a lot @phiz71

**Pull request merged**
